//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CafeOtomasyon.Model.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Hesap
    {
        public int id { get; set; }
        public int SiparisId { get; set; }
        public decimal ToplamTutar { get; set; }
        public System.DateTime Tarih { get; set; }
        public int OdemeId { get; set; }
        public int KullaniciId { get; set; }
    
        public virtual Siparis Siparis { get; set; }
        public virtual OdemeTuru OdemeTuru { get; set; }
        public virtual kullanici kullanici { get; set; }
    }
}
