//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CafeOtomasyon.Model.Entities
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class kafe_otomasyonDBEntities4 : DbContext
    {
        public kafe_otomasyonDBEntities4()
            : base("name=kafe_otomasyonDBEntities4")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Hesap> Hesap { get; set; }
        public virtual DbSet<İçecekKategori> İçecekKategori { get; set; }
        public virtual DbSet<İçecekler> İçecekler { get; set; }
        public virtual DbSet<kullanici> kullanici { get; set; }
        public virtual DbSet<Masa> Masa { get; set; }
        public virtual DbSet<OdemeTuru> OdemeTuru { get; set; }
        public virtual DbSet<Siparis> Siparis { get; set; }
        public virtual DbSet<SiparisDurumu> SiparisDurumu { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<Tatlı> Tatlı { get; set; }
        public virtual DbSet<Yemek> Yemek { get; set; }
        public virtual DbSet<YemekKategori> YemekKategori { get; set; }
        public virtual DbSet<Yetki> Yetki { get; set; }
    }
}
