//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CafeOtomasyon.Model.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class SiparisDurumu
    {
        public int id { get; set; }
        public int SiparisId { get; set; }
        public string Durum { get; set; }
        public Nullable<System.DateTime> SiparisAlınmaTarih { get; set; }
        public Nullable<System.DateTime> SiparisHazırlanmaTarih { get; set; }
        public Nullable<System.DateTime> TeslimEdilmeTarih { get; set; }
    
        public virtual Siparis Siparis { get; set; }
    }
}
